os: linux
sudo: required
language: generic

install:
  - sudo apt-get update -qq
  - sudo bash ./.avr-gcc-build.sh
  - avr-gcc --version

before_script:
  - wget https://github.com/stateos/IntrOS/archive/master.zip
  - unzip -q master.zip
  - mv -T IntrOS-master/IntrOS/kernel/ IntrOS/kernel/
  - rm -r IntrOS-master

script: make all GNUCC=avr-
